#my workflow

name: Mygithubactions
on:
  push:
      branches:
        - master
        
jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello
      run : echo "Hello from testing"
      
    
  my_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello
      run : echo "Hello from deploy"
    steps:
    - name: Print Hello,Hello
      run : echo "Hello,Hello"
      
      
    env:
      VAR1 : "Variable1"
      VAR2 : "Variable2"
    
  
